### ISSUE TITLE
User can add tags and remove them

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/code-journal#11]
## 💰 Motivation

While Journaling users can add tags

## 📐 Plan

add tags and remove when new entry and editing. Show tags in entries list

## 🖼️ Wireframes

![IMG_8837](https://user-images.githubusercontent.com/91447324/162339594-431fdaf9-a0b5-46db-900c-089380e9e556.jpg)

## ✅ Task List

- [ ] add tags input
- [ ] add plus button
- [ ] when tags input then show to the side of the bar (flex)
- [ ] when clicking on tags area then a X shows to the right side to cancel tags 
- [ ] in entries list page show tags
