### ISSUE TITLE
User can view and sort entries by date

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/code-journal#9]
## 💰 Motivation

A user can see the date that an entry is created and sort through newest to oldest and vise versa

## 📐 Plan

Allow users to sort through newest entries or oldest

## 🖼️ Wireframes

![IMG_8836](https://user-images.githubusercontent.com/91447324/162265159-f3213a69-3b60-402f-acaf-e5e593a7dcc4.jpg)

## ✅ Task List

- [ ] Add a date when the entry was created
- [ ] Show date in entries list page on every entry
- [ ] Make a select button with options new to old and old to new
- [ ] Allow User to sort entries page from oldest to newest
- [ ] Make sure DOM updates when sorted through date
- [ ] Clean up CSS
- [ ] Fix errors and functionality in private browser
- [ ] Try to break it
